docs/APIReference-Data-Conversion.md

[docs] Fix return type of convertFromRaw (See #28)

---

package.json

I watched somebody try to use node v0.12 and fail with cryptic messages. I meant to do this before we released anyway.

Check engines before building

---

README.md

Not so much important, but it adds interesting information about the current project status.
:beers:

Add Travis and NPM (version) badges to README.md

---

src/component/base/DraftEditor.css

I was just looking through the codez.

Fix some CSS classnames

---

gulpfile.js
package.json
src/component/base/DraftEditor.css
src/component/base/DraftEditorPlaceholder.css
src/component/utils/DraftStyleDefault.css

This lets us reuse the original files directly.

Transform cx modules in gulp

---

docs/Overview.md

This PR should help others avoid running into #42.

Add mention of UTF-8 meta tag to Overview docs.

---

examples/rich/rich.html

Reference on https://github.com/facebook/draft-js/issues/81

Fixing missing keys

---

src/model/transaction/__tests__/insertFragmentIntoContentState-test.js

Little code tweaks as suggested by @hellendag on PR #530 .

Code tweaks for FragmentIntoContentState tests

---

src/component/base/DraftEditor.css
src/model/encoding/convertFromHTMLToContentBlocks.js
src/model/transaction/__tests__/insertFragmentIntoContentState-test.js
src/model/transaction/insertFragmentIntoContentState.js

Appease internal lint prior to sync.

Lint fixes

---

docs/APIReference-EditorChangeType.md

**Summary**
Update documentation to reflect the recent block metadata changes shipped in 0.8.0.
**Test Plan**
None

Add change-block-data to EditorChangeType docs

---

website/core/Site.js

The previous GA account was vjeux's personal one :P Also it combined the data for several sites making it hard to disambiguate.

Put Draft.js on its own Google Analytics account

---

docs/APIReference-Data-Conversion.md
docs/Advanced-Topics-Block-Styling.md
docs/Advanced-Topics-Custom-Block-Render.md

- Including documentation for BlockRenderMap
- Updating the data conversion

Adding missing documentation to BlockRenderMap and updating documentation for data conversion

---

src/component/base/DraftEditorProps.js
src/model/paste/__tests__/DraftPasteProcessor-test.js

Hi,
this merge request fixes some minor issues.
It was created with help of [Feram][repo].
If it helped to improve this repository,
please consider to [star Feram's repo][repo] to show some love! 😊
PS:
The [Feram team][feramhq] is currently working on making this technology
available for everyone. If you want to be one of the first to use it,
please sign up up for the newsletter on [feram.co].
[repo]: https://github.com/feramhq/feram
[feramhq]: https://github.com/feramhq
[feram.co]: http://feram.co

Minor fixes

---

src/component/contents/DraftEditorContents.react.js

Fix React children mutation warning

---

examples/rich/rich.html
website/src/draft-js/index.js

Also sync rich example with homepage.

Enable tab/shift-tab in rich example

---

src/component/handlers/edit/editOnBeforeInput.js
src/component/handlers/edit/editOnKeyDown.js
src/component/handlers/edit/editOnPaste.js
src/model/transaction/__tests__/insertFragmentIntoContentState-test.js

Fix internal test failure and lint issues for internal sync.

Fix failing test and lint

---

docs/APIReference-Data-Conversion.md

Add parameter intro to convertFromHTML document(#643)

---

.eslintrc.js
src/model/modifier/RichTextEditorUtil.js

This will ensure Travis will fail for what were previously warnings.
This also fixes an existing issue.

Use a stricter lint config

---

src/component/handlers/edit/editOnPaste.js

**Summary**
Fix for #638
**Test Plan**
textBlocks is defined on line 88 `let textBlocks: Array<string> = [];` and therefore is always truthy. So this if statement was always inserting a fragment even when it shouldn't.

Edit on paste truthy fix

---

examples/tweet/tweet.html

I am playing with the tweet example and find there is a [unknown-prop-warning](https://facebook.github.io/react/warnings/unknown-prop.html). I fix the warning by this PR.

Fix react-unknown-prop warning in the tweet example

---

package.json
scripts/module-map.js

Restore 15.4 range, fix module-map

---

docs/APIReference-ContentState.md

Added code syntax to `\n`

---

src/component/base/DraftEditor.react.js
src/component/base/DraftEditorProps.js
src/component/handlers/composition/DraftEditorCompositionHandler.js
src/component/handlers/drag/DraftEditorDragHandler.js
src/component/handlers/edit/editOnBeforeInput.js
src/component/handlers/edit/editOnBlur.js
src/component/handlers/edit/editOnCompositionStart.js
src/component/handlers/edit/editOnCopy.js
src/component/handlers/edit/editOnCut.js
src/component/handlers/edit/editOnDragOver.js
src/component/handlers/edit/editOnDragStart.js
src/component/handlers/edit/editOnFocus.js
src/component/handlers/edit/editOnInput.js
src/component/handlers/edit/editOnKeyDown.js
src/component/handlers/edit/editOnPaste.js
src/component/handlers/edit/editOnSelect.js

This allows Flow to type them better and catch bugs.

Change handlers to pass `editor` as an argument

---

docs/APIReference-Data-Conversion.md

**Summary**
Fix broken link in Data Conversion documentation.
**Test Plan**
No functional changes.

Fix link in Data Conversion documentation.

---

gulpfile.js
src/component/base/DraftEditorPlaceholder.css

Facebook has renamed these; just keeping things in sync.

Update CSS Constants

---

README.md

*Before* submitting a pull request, please make sure the following is done...
1. Fork the repo and create your branch from `master`.
2. If you've added code that should be tested, add tests!
3. If you've changed APIs, update the documentation.
4. Ensure that:
* The test suite passes (`npm test`)
* Your code lints (`npm run lint`) and passes Flow (`npm run flow`)
* You have followed the [testing guidelines](https://github.com/facebook/draft-js/wiki/Testing-for-Pull-Requests)
5. If you haven't already, complete the [CLA](https://code.facebook.com/cla).
Please use the simple form below as a guideline for describing your pull request.
Thanks for contributing to Draft.js!
-
**Summary**
[Issue #865 - I have updated the Readme.md file to include getting started instructions based on the Draft.js …

Issue #865 Add 'Getting Started' section to `README`

---

src/component/base/DraftEditorPlaceholder.css
src/component/utils/DraftStyleDefault.css

Add missing 'permanent' to two CSS files

---

docs/Advanced-Topics-Block-Components.md

**Summary**
Clarifying the props passed into the custom block components
**Test Plan**
#541

block doc update

---

README.md
docs/Overview.md

**Summary**
Adds a notice to the readme and Overview Docs page to let users know the upcoming changes to the API.
#866

API Notice doc update

---

src/component/base/DraftEditor.react.js
src/component/base/DraftEditorProps.js

Fixes #890
(Will update this with changes in https://github.com/facebook/draft-js/pull/894 once that lands)

Add DraftEditorDefaultProps type

---

docs/Advanced-Topics-Custom-Block-Render.md

*Before* submitting a pull request, please make sure the following is done...
1. Fork the repo and create your branch from `master`.
2. If you've added code that should be tested, add tests!
3. If you've changed APIs, update the documentation.
4. Ensure that:
* The test suite passes (`npm test`)
* Your code lints (`npm run lint`) and passes Flow (`npm run flow`)
* You have followed the [testing guidelines](https://github.com/facebook/draft-js/wiki/Testing-for-Pull-Requests)
5. If you haven't already, complete the [CLA](https://code.facebook.com/cla).
Please use the simple form below as a guideline for describing your pull request.
Thanks for contributing to Draft.js!
-
**Summary**
just a small alignment change.
[...]
**Test Plan**
[...]

adjust js object alignment in documentation

---

CONTRIBUTING.md

Just another nudge to help folks with showing how a bug is reproduced.

Add link to the JSFiddle

---

README.md

Just update documentation to install with npm or Yarn. :)

Update README to install with Yarn

---

src/model/decorators/DraftDecorator.js

This change should help projects which uses draft-js with flow

Add DraftDecoratorStrategy type

---

CHANGELOG.md
docs/APIReference-Data-Conversion.md
docs/APIReference-Editor.md
docs/Advanced-Topics-Block-Components.md
docs/Advanced-Topics-Decorators.md
docs/Advanced-Topics-Entities.md
docs/Advanced-Topics-Inline-Styles.md
docs/Advanced-Topics-Managing-Focus.md
docs/QuickStart-API-Basics.md
docs/QuickStart-Rich-Styling.md
package.json
website/server/convert.js

*Before* submitting a pull request, please make sure the following is done...
1. Fork the repo and create your branch from `master`.
2. If you've added code that should be tested, add tests!
3. If you've changed APIs, update the documentation.
4. Ensure that:
* The test suite passes (`npm test`)
* Your code lints (`npm run lint`) and passes Flow (`npm run flow`)
* You have followed the [testing guidelines](https://github.com/facebook/draft-js/wiki/Testing-for-Pull-Requests)
5. If you haven't already, complete the [CLA](https://code.facebook.com/cla).
Please use the simple form below as a guideline for describing your pull request.
Thanks for contributing to Draft.js!
-
**Summary**
[...]
**Test Plan**
[...]

#links point to draft-0-10-0 examples

---

docs/APIReference-APIMigration.md

Fix the arguments order and quantity in the decorators strategy accordingly to the code expectations https://github.com/facebook/draft-js/blob/7390e2972145494146202c3d3480eb9509dc90d4/src/model/decorators/CompositeDraftDecorator.js#L71

documentation: fix the arguments in the decorators

---

docs/APIReference-SelectionState.md

add code that make it more easier to understand how the myContentBlock can be obtained for the SelectionState

add the code to show how obtain myContentBlock

---

docs/APIReference-APIMigration.md
docs/Advanced-Topics-Decorators.md

Fixes #973
**Test Plan:**
Manually tested the website and verified changes.

Fix order of arguments for decorator strategy in docs

---

docs/APIReference-Entity.md
docs/Advanced-Topics-Entities.md

**Corrected links to migration guide on entity pages**

Corrected link to migration guide on entity pages

---

package.json
src/.flowconfig
src/component/selection/expandRangeToStartOfLine.js
src/model/paste/getSafeBodyFromHTML.js

Update flow to 0.38

---

CONTRIBUTING.md

This is mainly to address internal and external questions about future API breaking changes.
Also added the Code of Conduct along the way.

Update contributors doc

---

website/core/Site.js

**Summary**
Updated the year in the footer from 2016 to 2017.

Update copyright year to 2017 in footer on website

---

meta/meeting-notes/2017-02-17-weekly-meeting.md

Add meeting notes from 02-17-17

---

meta/meeting-notes/2017-02-24-weekly-meeting.md

Add meeting notes from 02/24/17

---

docs/Advanced-Topics-Entities.md

Fixed a wrong sentence in **Creating and Retrieving Entities**.

Update Entities docs in Advanced Topics section

---

docs/APIReference-ContentState.md

Fixed ContentState.createEntity docs 

---

package.json
src/component/base/__tests__/DraftEditor.react-test.js
src/component/contents/__tests__/DraftEditorBlock.react-test.js

Fixes https://github.com/facebook/draft-js/issues/1157

Fix errors from react update

---

CHANGELOG.md
package.json

Meant to push this commit onto https://github.com/facebook/draft-js/pull/1177 in response to @spicyj's helpful suggestion.

Add changelog link

---

src/component/base/DraftEditor.react.js
src/component/contents/DraftEditorBlock.react.js
src/component/contents/DraftEditorTextNode.react.js

Removed unnecessary invariant usage and made sure flow still passes.

Removed unnecessary invariant usage

---

docs/APIReference-Editor.md

Let's merge this when releasing v0.11.0
See #1036

Add documentation about textDirectionality prop

---

meta/meeting-notes/2017-05-19-weekly-meeting.md
meta/meeting-notes/2017-05-26-weekly-meeting.md

Just keeping this updated. Shouldn't need review.

Add meeting notes from last two weeks

---

meta/meeting-notes/2017-06-02-weekly-meeting.md

Add weekly meeting notes

---

website/src/pages/index.js
website/src/pages/styles.module.css

Removing social banner from the main page

Removing banner

---

website/docusaurus.config.js
website/src/pages/styles.module.css

Our mission at [Meta Open Source](https://opensource.facebook.com/) is to empower communities through open source, and we believe that it means building a welcoming and safe environment for all. As a part of this work, we are adding this banner in support for Ukraine during this crisis.

Adding Social Banner in Support of Ukraine
