docs/Advanced-Topics-Inline-Styles.md

This looks like the file that generates this page:  http://facebook.github.io/draft-js/docs/advanced-topics-inline-styles.html
Updating two links to point to the correct path.

Update broken example links in Inline Styles doc

---

docs/Advanced-Topics-Block-Components.md
docs/Advanced-Topics-Block-Styling.md
docs/Advanced-Topics-Decorators.md
docs/Advanced-Topics-Entities.md
docs/Advanced-Topics-Inline-Styles.md
docs/Advanced-Topics-Key-Bindings.md
docs/QuickStart-API-Basics.md
docs/QuickStart-Rich-Styling.md

This can be done to quite a few more documents. Should I do separate PRs for each or can I group as one larger syntax highlighting addition PR?

Add syntax highlighting to API Basics documentation

---

docs/Advanced-Topics-Block-Components.md
docs/Advanced-Topics-Block-Styling.md
docs/Overview.md
docs/QuickStart-API-Basics.md
docs/QuickStart-Rich-Styling.md

Change examples to use ES6 Classes. Closes #7

[docs] Change examples to use ES6 Classes

---

examples/entity/entity.html
examples/link/link.html

`convertToRaw` expects a `ContentState` object.
Note that the `logState` functions in `plaintext.html` and `tweet.html` just call `.toJS()` without a `convertToRaw`.

Fix logState calls in entity and link examples

---

docs/Advanced-Topics-Entities.md

Currently links to https://facebook.github.io/draft-js/docs/docs/advanced-topics-block-components.html which has /docs/ repeated twice. =P

[docs] Fix broken link in Advanced Topics Entities

---

docs/QuickStart-Rich-Styling.md

In `_onBoldClick`, `editorState` wasn't defined and caused the Bold button to become inoperable.

Fix typo in QuickStart-Rich-Styling.md

---

docs/APIReference-Editor.md
docs/Advanced-Topics-Block-Styling.md
docs/Advanced-Topics-Key-Bindings.md
docs/Advanced-Topics-Text-Direction.md

I found a few typos in the docs that I though needed some fixing :)

Fix typos in docs

---

website/package.json

- git cloned the repo
- npm install && npm build
- went to /website
- npm start
- went to http://localhost:8080/draft-js/index.html :
This PR creates src/draft-js/lib/ dir as part of postintall script.

Fix missing src/draft-js/lib/ dir

---

examples/link/link.html

The `content` constant is defined but never used inside `_removeLink` and `_addLink`

removed two instances of unused content constants.

---

docs/Advanced-Topics-Key-Bindings.md
src/Draft.js

In [Advanced Topics: Key Bindings](https://facebook.github.io/draft-js/docs/advanced-topics-key-bindings.html) there is an [example](https://facebook.github.io/draft-js/docs/advanced-topics-key-bindings.html#example) where both `getDefaultKeyBinding()` and `KeyBindingUtil` are used, but neither are exported by `draft-js`. This PR exports both `getDefaultKeyBinding()` and `KeyBindingUtil` from `draft-js`.
Also in the above example, `getDefaultKeyBinding()` was not imported. This PR adds `getDefaultKeyBinding()` to the imports for the example.
Fixes #87 and #88.

Export getDefaultKeyBinding and KeyBindingUtil

---

src/model/encoding/convertFromHTMLToContentBlocks.js
src/model/paste/__tests__/DraftPasteProcessor-test.js

Test cases pretty much explain what's going on. This will handle inline styles being unset further down in the dom tree. 
This fixes #481

Add style un-setting to paste handler

---

examples/media/media.html

fixes #463
this fixes two things:
1. it fixes #463 where if you inserted a blank string for a piece
of media the editor state would be set to null.
2. the media example no longer uses window.prompt which previously
broke selection state. instead using an input like the link example.
it should be noted though that with this commit it's possible to
insert a blank url for media. i initially was going to add protection
for this, but after looking at the link example it appears the link
example doesn't care if you enter a blank link.
looking at the media objects generated for mp3/mp4 the play bar is still
there, and image is a whitespace. i'll happily add in a safeguard if
it's determined that's "unwanted" behavior. however I decided to stick
with consistency with the other examples for this …

removes window.prompt from media example

---

package.json

This should ensure that Flow will pass and nobody should get stuck with
a version of fbjs that isn't compatible with the version of Flow we use.

Update fbjs dep to 0.8.3

---

src/.flowconfig

**Summary**
I'm not sure why we need to change this. The magic bit seems to be needing to match the newline, the rest of the changes just bring use more in line with the internal flowconfig. Maybe @jeffmo can tell us why?
**Test Plan**
`npm run flow`

Update Flow comment supression regex

---

src/model/encoding/convertFromHTMLToContentBlocks.js

**Summary**
`mailto:` links were being stripped to plaintext on paste because they failed the protocol check.
For now I added it to the list of accepted protocols, but I was wondering if it might be reasonable to remove this check altogether and allow pasting links with any protocol? Or perhaps making this configurable.
**Test Plan**
There are no tests for `convertFromHTMLToContentBlocks` yet. I'd prefer to add cases to an existing test file rather than starting a new one, unless absolutely necessary.

Accept pasted mailto: links

---

src/model/transaction/__tests__/insertFragmentIntoContentState-test.js
src/model/transaction/insertFragmentIntoContentState.js

**Summary**
Fixes a situation when you insert new blocks with metadata,
eg using Modifier.replaceWithFragment. If the fragment have data,
it wouldn't be present on the resulting ContentState.
insertFragmentIntoContentState now uses the metadata of the
block or blocks inserted.
Also, included tests for insertFragmentIntoContentState.
**Test Plan**
It's possible to observe the results of Modifier.replaceWithFragment when the fragment have block-level-metadata, before the fix, the resulting ContentState will not contain the metadata from the new blocks, and after the fix, the metadata will be there.

Use block level metadata into fragment insertion

---

.travis.yml
package.json

**Summary**
- reorder for better readability
- add the Node v4 build requirements
- start pruning and updating npm deps so the cache doesn't get stale
**Test Plan**
- `travis-lint` only reports issue with `apt` key but is a bug with their tool
- testing it live on Travis here now

Update Travis CI config

---

src/component/base/DraftEditor.css

fixes #214
thanks to @bradleyayers excellent digging it turns out there's a
CSS property you can assign to disable the bold/italics/underline
for iOS. although you can techincally apply this style seperately
, since the editor breaks due to the unexpected dom mutations i
think it's best if this actually gets defaultly added to the root
of the editor. which this commit does.

removes iOS format tooltips everywhere

---

src/component/selection/__tests__/getDraftEditorSelection-test.js
src/component/selection/getSelectionOffsetKeyForNode.js

Decorator do not have `data-offset-key` attribute. Fix the implementation of `getSelectionOffsetKeyForNode` function to resolve the `data-offset-key` from decorator's children and fix tests.
Related issue https://github.com/facebook/draft-js/issues/476

Decorator do not have `data-offset-key` attribute. Fix `getSelectionOffsetKeyForNode` function

---

src/component/base/DraftEditor.css

**Summary**
turns out chrome (at least) would incorrectly not erase the placeholders
with -webkit-user-modify being applied where it was.
this was totally an oversight on my part not testing after taking
the lucidity designs comment in PR 509.
Testing this time in my normal suite of browsers (firefox, chrome, safari)
this commit moving the selection state to just target .public/DraftEditor/content
fixes the selection state problem.
**Test-Plan**
1. Build the project.
2. Open up the rich content example.
3. Notice the placeholder text goes away when you type.

fixes selection-state with -webkit-user-modify

---

src/model/encoding/convertFromHTMLToContentBlocks.js

Making sure that entities also support other common attributes for importing from html and pasting content. This is very important for compatibility with already existing applications

Adding more attributes to convertFromHTMLToContentBlocks entity whitelist

---

docs/APIReference-RichUtils.md

**Summary**
This is a small update to the docs to specify the proper return type for `tryToRemoveBlockStyle`.

Docs: Update return type for `tryToRemoveBlockStyle`

---

docs/APIReference-Editor.md
src/component/base/DraftEditor.react.js
src/component/base/DraftEditorProps.js
src/component/contents/DraftEditorBlock.react.js
src/component/contents/DraftEditorContents.react.js
src/component/contents/DraftEditorLeaf.react.js

cc @hellendag
Note, I also considered making `customStyleMap` and `customStyleFn` mutually exclusive, where if the latter were specified, then the former would materialize a function with the current behavior and only pass down `customStyleMap` to the leaf component -- but, then you'd lose the default behavior, which seems a little aggressive.
I think as long as it's clear that `customStyleFn` will execute after any `customStyleMap` additions then this is fine.
The downside here, is that just specifying a `customStyleFn` means that the default draft styles will always apply and you'd have to overwrite them to stop it (which is the current situation anyway).

Adds customStyleMap for more control over inline style ranges #342

---

src/component/base/DraftEditor.css

**Summary**
The introduction of `user-modify: read-write-plaintext-only;` ends up breaking readOnly editors with nested editable content, as the cursor jumps back to the top-level editor when focus changes.
Fix this by applying the `user-modify` value only if the content node is editable.
**Test Plan**
- Run TeX editor.
- Click a formula. Type inside the textarea. Verify that I can do so.

Fix nested editable elements in readOnly editor

---

package.json

compiled code now requires `object-assign` due to a new transform
Fixes #593

Include object-assign in deps

---

examples/tex/package.json

Fixes an issue that occurred when trying to run `npm start` on the tex example.
`babel-loader@6.2.4 requires a peer of babel-core@^6.0.0 but none was installed.`

Tex example deps fix

---

docs/APIReference-Editor.md
docs/Advanced-Topics-Key-Bindings.md
src/component/base/DraftEditorProps.js
src/component/handlers/drag/DraftEditorDragHandler.js
src/component/handlers/edit/editOnBeforeInput.js
src/component/handlers/edit/editOnKeyDown.js
src/component/handlers/edit/editOnPaste.js
src/component/utils/isEventHandled.js
src/model/constants/DraftHandleValue.js

Changes for https://github.com/facebook/draft-js/issues/339
@hellendag I'm not personally happy with all the literal `'handled'` strings now. The same counts for every usage of string literals, like the values of `DraftRemovalDirection`, `DraftBlockType` or any other type value. What are your thoughts on extracting them into constant files and using those constants instead?
Something along these lines:
```js
import { HANDLED } from 'DraftHandleValueConstants';
/*...*/
handleReturn(e) {
return HANDLED;
}
/*...*/
```
Since we already have those values to create the flow types, is that maybe a point where we can hook in to generate those constants, so we wouldn't have to duplicate them in two files?

Convert handler signature to return a `DraftHandleValue` value, instead of a boolean - #339

---

src/model/encoding/convertFromDraftStateToRaw.js

**Summary**
Previously, `convertFromDraftStateToRaw` stripped the depth of all non-list blocks, making it difficult to implement custom block types that support depth/indentation. This seems a bit arbitrary since `convertFromDraftStateToRaw` is the only code in Draft with this restriction; the rest of the code does allow depth to be set on any block, and convertFromRawToDraftState` does allow depths to be specified at import time on any block type.
This change causes `convertFromDraftStateToRaw` to always export the block depth regardless of block type.
**Test Plan**
All existing tests pass, and I don't believe this change warrants any additional test coverage.
fixes #381

Preserve depth of all block types when converting to raw

---

src/model/immutable/DraftBlockRenderConfig.js

This is currently getting rewritten as `./react`. We could probably do this by adding react to the alias list but Flow currently has global types for React. It will for some time so we can just use them.
Note: internally at FB we alias this type to `ReactElement` directly so this will be a bit out of place but there are some uses. I chose to use this here since the resulting type is being used in the outside world.

Remove react import, use React$Element

---

docs/Advanced-Topics-Block-Styling.md
docs/QuickStart-Rich-Styling.md

Updating documentation to say handleKeyCommand returns 'handled' or 'not-handled' (the DraftHandleValue type) as opposed to true or false (boolean type)

update handleKeyCommand docs to return DraftHandleValue

---

website/src/draft-js/css/draft.css

We have [a PR to add a new page to the docs,] and it includes a table
showing the mapping of block types to elements. However, we don't have
good styles for tables in the documentation.
[a PR to add a new page to the docs,]: https://github.com/facebook/draft-js/pull/387
Adding these styles should unblock that PR so we can merge it and update
the Draft.js website.
I've attached a 'before' and 'after' screenshot of the new docs to show how these styles will help:
**Before:**
**After:**

Add table styles to documentation

---

src/model/modifier/RichTextEditorUtil.js

**Summary**
When i make a selection when the last block is an atomic block and put an H2 style, it broke the block because "hasAtomicBlock" evaluates to false.
1 - write some text "this is a text block"
2 - add atomic block
3 - push shift and up arrow key to select the atomic block and the text "this is a text block"
4 - select H2 or another blockType.
5 - atomic block brokes
With this changes the last block selected is also analysed in search of atomic block.
**Test Plan**
1 - write some text "this is a text block"
2 - add atomic block
3 - push shift and up arrow key to select the atomic block and the text "this is a text block"
4 - select H2 or another blockType.
5 - atomic block is not broken

#648 - Include endKey selected block on hasAtomicBlock analysis

---

.github/ISSUE_TEMPLATE.md

**Summary**
When users open new issues, they should have a basic jsfiddle that they can start with. Added a link to a base Draftjs example here (https://jsfiddle.net/stopachka/m6z0xn4r/)
**Test Plan**
- Verify that https://jsfiddle.net/stopachka/m6z0xn4r/ is indeed a sufficient jsfiddle to get started with Draft
- Verify that the issue template is based on the file being edited

Add an example jsfiddle to the issue template

---

package.json

I upgraded eslint-config-fbjs recently which changed a peerDep for better Flow linting. New installs are going to pick that up and get a warning so we should fix it.
Fixes #645

Upgrade eslint-config-fbjs & switch flow plugin

---

src/model/modifier/RichTextEditorUtil.js

**Summary**
Previously, RichUtils "removed" atomic blocks via removeRangeFromContentState. This was problematic, because it preserves the atomic block properties and merges the end block content, resulting in behavior where atomic block data would transfer to unstyled blocks.
This change addresses those issues by removing the atomic block entirely from the blockMap and preserving the existing selection.
**Test Plan**
given the following blockMap in an Editor which is using RichUtils' handleKeyCommand
```
[
{
"key": "2124c",
"text": "abc",
"type": "unstyled",
"depth": 0,
"inlineStyleRanges": [],
"entityRanges": [],
"data": {}
},
{
"key": "6ud8",
"text": "",
"type": "atomic",
"depth": 0,
"inlineStyleRanges": [],
"entityRanges": [],
"data": {
"type": "image",
"src": 1684980,
"operation": …
```

RichUtils onBackspace: remove entire atomic block

---

examples/tweet/tweet.html

This PR fixes the broken "tweet" example.
The example ceased to function due to changes in #376.
`contentState` is now the first argument to the strategy functions.

Fix tweet example: add missing contentState argument

---

package.json
src/.flowconfig
src/component/handlers/drag/DraftEditorDragHandler.js

**Note:** This has already been included in [the 0.9.0-stable release branch](https://github.com/facebook/draft-js/tree/0.9-stable), but we need to keep master updated as well.
Version 0.32.0 of Flow introduced a flow error into Draft.js. We are
using 0.32.0 internally at Facebook and need to fix this Flow error in
order to upgrade to Draft.js 0.9.0 internally.

Update Flow version to 0.32.0; fix flow error in DraftEditorDragHandler

---

src/model/encoding/convertFromRawToDraftState.js

**Summary**
`convertFromRawToDraftState` had a typo in the code, `keyseq` should have been `keySeq`.  Seen on #660
**Test Plan**
- Run the `entity` example, and make sure the convertFromRaw function works

fix typo in convertFromRawToDraftState

---

docs/Advanced-Topics-Issues-and-Pitfalls.md

The issue with 'React ContentEditable Warning' was resolved when React
added the 'suppressContentEditableWarning' option([1]) and then we used it
in Draft.js([2]). This doesn't need to be in the docs any more.
[1]: https://github.com/facebook/react/pull/6112
[2]: https://github.com/facebook/draft-js/pull/98

Update docs to remove 'React ContentEditable Warning' issue

---

examples/entity/entity.html
examples/link/link.html
examples/media/media.html

**Edit: This now fixes the media example as well as the link example.**
The link and media examples were using an outdated syntax that changed
in [#376](https://github.com/facebook/draft-js/pull/376).
Old syntax:
```
const entityKey = Entity.create('LINK', 'MUTABLE', {url: urlValue});
```
Correct:
```
const contentStateWithEntity = contentState.createEntity(
'LINK',
'MUTABLE',
{url: urlValue}
);
const entityKey = contentStateWithEntity.getLastCreatedEntityKey();
```
Also while working on this, removed the 'require' of 'Entity' in the
'entity' example.
This closes #676

Fix link example

---

docs/QuickStart-Rich-Styling.md

The Rich Styling article linked to `EditorState` docs when referencing the `RichUtils` module, instead of linking to the `RichUtils` docs.

Fix URL linking to RichUtils module in documentation

---

package.json

This fixes 2 issues when Draft is a dependency of a project that is
using Flow.
- `typeof` import now rewritten correctly
- `__DEV__` declaration is now inlined
Here's the diff on master right now: https://gist.github.com/zpao/641b31feae17be7e3e1fabc9aecd10a3
Note: this doesn't impact anything internal and is only for the npm package.

Upgrade babel-preset-fbjs

---

src/component/base/DraftEditor.react.js
src/component/handlers/composition/DraftEditorCompositionHandler.js
src/component/handlers/drag/DraftEditorDragHandler.js
src/component/handlers/edit/editOnBeforeInput.js
src/component/handlers/edit/editOnBlur.js
src/component/handlers/edit/editOnCompositionStart.js
src/component/handlers/edit/editOnCopy.js
src/component/handlers/edit/editOnCut.js
src/component/handlers/edit/editOnFocus.js
src/component/handlers/edit/editOnInput.js
src/component/handlers/edit/editOnKeyDown.js
src/component/handlers/edit/editOnPaste.js
src/component/handlers/edit/editOnSelect.js

If you type Option-E, Backspace, then the in-progress accented character should be deleted. Similarly, in 2-Set Korean, if you press A, Backspace, the character should be deleted. Both of these don't work correctly yet, but this commit fixes it.
Currently, when you press Backspace, we are in composition mode and we receive a compositionend event then a keydown event for the backspace. Our composition handler doesn't exist composition mode immediately but rather waits 20ms to see if it gets a compositionstart event immediately (and if so, does not exit). It seems like if we receive a compositionend event then a keydown, we always want to exit composition mode immediately and re-interpret the keydown in edit mode. Here I do so.
This change is made trickier by the fact that each event …

Fix dead key deletion

---

src/component/base/DraftEditor.react.js
src/component/handlers/edit/editOnSelect.js

I can't describe entirely why the DraftEditor.react change here is necessary, but this is closer to what we had before #666.
The editOnSelect change fixes holding down Backspace in Firefox -- before this, the cursor would jump to the start of the input.

Fix repeated backspace, other internal components

---

examples/link/link.html

**Summary**
When adding a new link on top of another link, pre-fill the input with the current url value. Use-case described in details here: https://github.com/facebook/draft-js/issues/732
I believe the example enhancement will be useful for other developers too.
**Test Plan**
I loaded the example and manually tested on Chrome / Safari / Firefox / Opera latest.

Feature / Link Example: Pre-fill the URL Input with the Current URL (if any)

---

docs/APIReference-EditorState.md

**Summary**
The docs for `EditorState.setInlineStyleOverride` leave out the initial `editorState` argument. This just adds that in.
**Test Plan**
N/A

Update api docs for EditorState.setInlineStyleOverride

---

docs/APIReference-Data-Conversion.md

**Summary**
This doc page is the first place people find when looking for information on convertFromHTML but the original code sample is not very useful. This hopefully will give people a better idea of how to use the function and then a reference to where I found the code snippet.
Should close #236 as well.

[documentation] Include reference to example for convertFromHTML

---

package.json

It appears that some change in React 15.4.0 is causing builds to fail in
CI. [See issue #779.](https://github.com/facebook/draft-js/issues/799)
While we figure that out, let's limit the versions that will be used.

Temporarily limit versions of React allowed

---

src/.flowconfig

Flow wasn't finding the 'ReactDOM' node module. In the past it was (I
assume) finding this dependency inside of the React package - but in
React 15.4.0 the "secret" copy of ReactDOM was split out completely
into it's own module.[1]
It seems like we should be able to use `scripts/module_map.js` to
specify the mapping of `ReactDOM` to `react-dom` but updating that was
not making a difference to Flow, so I added a mapping option to the flow
config.
[1]: https://facebook.github.io/react/blog/2016/11/16/react-v15.4.0.html#separating-react-and-react-dom

Fix flow typing of 'ReactDOM'

---

examples/convertFromHTML/convert.html
examples/entity/entity.html
examples/link/link.html
examples/tweet/tweet.html
src/Draft.js
src/component/handlers/edit/editOnPaste.js
src/model/decorators/CompositeDraftDecorator.js
src/model/decorators/DraftDecorator.js
src/model/decorators/__tests__/CompositeDraftDecorator-test.js
src/model/encoding/convertFromHTMLToContentBlocks.js
src/model/encoding/convertFromRawToDraftState.js
src/model/entity/DraftEntity.js
src/model/entity/__mocks__/DraftEntity.js
src/model/entity/__tests__/DraftEntity-test.js
src/model/immutable/ContentState.js
src/stubs/ComposedEntityType.js

**Summary**
A previous PR had completely removed 'DraftEntity' the module and moved
control over entities into ContentState.[1] This changed several public
APIs of Draft.js in a non-backwards compabible way.
[1]: https://github.com/facebook/draft-js/pull/376
To make it easier to migrate multiple use cases to the new Draft.js API,
and because the transition is too complex for a simple codemod, we are
releasing a version that supports both the new and the old API and then
later releasing a version that breaks the old API completely.
In order to renew support for the old API while also supporting the new
API, this PR
- restores the DraftEntity module and associated tests/mocks
- calls into DraftEntity methods under the hood of the new API
We tried to leave as much of the new API code in …

Deprecate DraftEntity before removing

---

src/component/handlers/edit/editOnSelect.js

(Landed at Facebook as D4056089 over a month ago, copying back out.)
Summary:
If we have a state update enqueued but the rerender hasn't happened, and a select event comes in, we can't do anything useful with it because although we could compare the last rendered editor state with the DOM selection, we can't make a rational choice for how to update the latest queued editor state with the DOM selection. (Previously, this code was throwing away any content change which would lead to a loss of inserted chars in many Windows IME scenarios.)
In particular, if you type in Korean w/ Windows IME then press space,
* compositionend arrives, causing us to set a 20ms timeout for resolving the composition,
* at that time, the text is already inserted in the DOM
* then keydown 32 comes in, which (due …

Improve typing in Korean on Windows

---

docs/Advanced-Topics-Custom-Block-Render.md
src/model/encoding/__tests__/convertFromHTMLToContentBlocks-test.js
src/model/encoding/convertFromHTMLToContentBlocks.js
src/model/immutable/DefaultDraftBlockRenderMap.js
src/model/immutable/DraftBlockRenderConfig.js

**Summary**
When pasting adjacent paragraphs were converged into a single paragraph, by introducing the idea of alias for an element we can then keep there rendering elements at the same time as provide different element matches.
This issue is also referenced at: https://github.com/facebook/draft-js/issues/523 and https://github.com/facebook/draft-js/issues/395
**Test Plan**
We can test by running `npm test` or by pasting content from a word processing tool such as word into draft. Paragraphs should be now treated as a separate blocks and should no longer get converged into a single one.

Fix line breaks when pasting from word to draft

---

src/model/immutable/ContentState.js

As part of the changing API the signature of
contentState.createFromBlockArray changed.
At some point (recently I think) this was changed to no longer support
the old API, and we didn't quite have the 0.9.1 style examples in place,
so it wasn't caught.
This adjusts the 'createFromBlockArray' to work with both the old and
new APIs.

Make contentState.createFromBlockArray work with old and new API

---

examples/draft-0-10-0/tex/js/modifiers/insertTeXBlock.js
src/model/encoding/convertFromHTMLToContentBlocks.js
src/model/encoding/convertFromRawToDraftState.js
src/model/entity/DraftEntity.js
src/model/entity/__tests__/DraftEntity-test.js
src/model/entity/__tests__/getEntityKeyForSelection-test.js
src/model/entity/getEntityKeyForSelection.js
src/model/immutable/ContentState.js
src/model/modifier/RichTextEditorUtil.js
src/model/modifier/getCharacterRemovalRange.js
src/model/paste/__tests__/DraftPasteProcessor-test.js
src/model/transaction/__tests__/removeEntitiesAtEdges-test.js
src/model/transaction/removeEntitiesAtEdges.js

We are deprecating the old DraftEntity API and this adds warnings for folks still using the outdated syntax.
Why is the API changing? Because
- currently changing or adding entities won't trigger a re-render
- the use of a non-Immutable storage for entities doesn't fit well with
the rest of the Draft architecture
- moves Entity storage out of global module; this just makes more sense
as an API, rather than having it globally available.
This moves the logic for the old API into private methods, and adds
warnings and comments around the public-but-deprecated API methods.
We then use the private methods internally while we still support both
APIs.
A future version of Draft will actually remove the old API completely,
and these warnings and comments will help folks make updates to their
code …

Part two deprecate but dont delete old entity api

---

src/component/base/DraftEditor.react.js
src/component/handlers/edit/editOnBeforeInput.js
src/component/handlers/edit/editOnInput.js

Fixes #92.
If an onChange handler replaces every "x" with an "abc", then when you type "x", we trigger onChange from beforeinput and rerender immediately with the content "abc", then the browser still inserts an "x" character!
This fix is surprisingly simple: instead of triggering an update during beforeinput, we simply wait until the input event to do so. This means that when we rerender, the browser would have already inserted the "x" character and React will correctly delete it when rerendering.
Test Plan: In plaintext example, change the handler to
```
this.onChange = (editorState) => {
var content = editorState.getCurrentContent();
return this.setState({
editorState: EditorState.set(editorState, {
currentContent: Modifier.removeInlineStyle(content, content.getSelectionAfter(), …
```

Fix modifying state during onChange triggered by beforeinput

---

src/component/base/DraftEditor.react.js
src/component/contents/__tests__/DraftEditorBlock.react-test.js
src/component/handlers/edit/editOnCompositionStart.js
src/component/handlers/edit/editOnPaste.js
src/component/handlers/edit/editOnSelect.js
src/model/encoding/__tests__/convertFromHTMLToContentBlocks-test.js
src/model/encoding/__tests__/decodeEntityRanges-test.js
src/model/encoding/convertFromHTMLToContentBlocks.js
src/model/entity/DraftEntity.js
src/model/immutable/CharacterMetadata.js
src/model/immutable/ContentState.js
src/model/immutable/EditorState.js
src/model/immutable/EntityMap.js
src/model/modifier/RichTextEditorUtil.js
src/model/transaction/addEntityToContentState.js
src/model/transaction/addEntityToEntityMap.js
src/model/transaction/createEntityInContentState.js
src/model/transaction/updateEntityDataInContentState.js

This is a collection of flow and lint fixes that came up when testing the 0.10.0-stable branch internally.
I'm not completely sure why they don't show up when we run eslint and flow locally or in CI.
Hopefully nothing controversial, and in a couple of cases they are short-term fixes to accomodate supporting two APIs until we release 0.11.0. More info in each commit message.

Fix lints and flow errors for v0.10

---

src/model/encoding/convertFromHTMLToContentBlocks.js
src/model/encoding/convertFromRawToDraftState.js
src/model/entity/DraftEntity.js
src/model/entity/__tests__/DraftEntity-test.js
src/model/entity/__tests__/getEntityKeyForSelection-test.js
src/model/entity/getEntityKeyForSelection.js
src/model/immutable/ContentState.js
src/model/modifier/RichTextEditorUtil.js
src/model/modifier/getCharacterRemovalRange.js
src/model/paste/__tests__/DraftPasteProcessor-test.js
src/model/transaction/__tests__/removeEntitiesAtEdges-test.js
src/model/transaction/removeEntitiesAtEdges.js

Private methods should not be called as public methods. A recent PR
(https://github.com/facebook/draft-js/pull/814) added warnings to the
public-but-deprecated API of DraftEntity, and then moved the logic for
those methods into private methods that can be called within the
Draft.js framework.
These methods are "private" in the sense that we are only calling them
within Draft. They should not be used outside of the Draft library,
because they will be removed in an upcoming version of the library.
We have a transform step that causes issues when an underscore-prefixed
method is called outside of it's module, so changing the method names
seems like the easiest way to deal with this issue and still send the
message that they are private.

Change underscore method names to bypass lint about private methods

---

src/model/decorators/CompositeDraftDecorator.js
src/model/decorators/DraftDecoratorType.js
src/model/decorators/__tests__/CompositeDraftDecorator-test.js
src/model/immutable/BlockTree.js
src/model/immutable/EditorState.js
src/model/immutable/__tests__/EditorState-test.js

This change fixes #859 by reversing the order of the arguments to `getDecorations`. Existing decorators will continue to function as they had in 0.9 since they can safely ignore the new `ContentState` parameter. Without this change existing decorators like `MultiDecorator` in `draft-js-plugins` will need to be broken making it more difficult to migrate to 0.10 for existing users of `draft-js-plugins`.
The backwards compatibility break appears to be unintentional as the other breaks introduced by #376 were fixed by #790. This closes a break missed by #790.

Fix 0.10 compatibility break in getDecorations

---

docs/Advanced-Topics-Entities.md

**Summary**
There has been some confusion over the params passed into `applyEntity`. Since targetRange is an instance of `SelectionState`, lets make the docs more clear. #455 
**Test Plan**
Doc change only.

Update applyEntity doc

---

docs/APIReference-EditorState.md

**Summary**
We reference using `Editor.set()` in the docs, as well as in multiple examples. I've updated docs to reference it (#579). However, the reason it wasn't there is because it's a method that is on Immutable's `Record` class.  I know we don't want to recommend these methods, but since we are using it in the examples it may not be a bad idea to at least include a reference to it. That said, feel free to suggest a better way to word this, or to just reject it.

EditorState.set()

---

src/component/selection/getRangeBoundingClientRect.js

**Summary**
This patch fixes getVisibleSelectionRect for webkit based browsers. The bad behavior is described in the issues #570 and #290.
**Test Plan**
In Chrome, selecting a wrapped line will return top values higher than expected, after applying this patch, the value should match the visual selection.

Ignores 0 width rects when calculating selection

---

src/model/immutable/EditorState.js
src/model/immutable/__tests__/EditorState-test.js

Another attempt at fixing #412 and #672 and added a test for not discarding override styles when adjusting depth.

Prevent discarding style override on split-block

---

docs/APIReference-Editor.md
src/component/base/DraftEditorProps.js
src/component/contents/DraftEditorBlock.react.js
src/component/contents/DraftEditorLeaf.react.js

Recently, `customStyleFn` was added for more flexibility to specify styles: https://github.com/facebook/draft-js/issues/342 / https://github.com/facebook/draft-js/pull/354
This PR proposes an addition to that same API, to allow the block type to be taken into consideration, as well. Block type is important for cases where, for example, bold requires a different CSS object result for different font families:
```
const customStyleFn = (style, block) => {
const isBold = style.has('BOLD')
if (isBold) {
if (block.getType() === 'code-block') {
return {
// fontFamily remains as normal (monospace)
fontWeight: '700',
}
} else {
return {
// fontFamily changes from normal to demi
fontFamily: 'MyFont-Demi',
fontWeight: '700',
}
}
}
return {}
}
```
By adding `block` to the callback, it opens avenues …

Pass `block` to `customStyleFn` callback

---

src/model/immutable/CharacterMetadata.js

**Summary**
In the CharacterMeta file, to lookup if a certain CharacterMeta had a style, we were using .has, which looks up keys in an array, while something like 'ITALIC' is stored as a value, so Immutable's .includes function would be more appropriate here.

Fix array lookup to .includes rather than .has

---

package.json
src/.flowconfig
src/component/handlers/edit/editOnBeforeInput.js
src/component/handlers/edit/editOnSelect.js
website/package.json

This fixes some issues with the fix originally merged from PR #667
Credit to @spicyj  and @srmcconomy for this fix. 
For now I'm just getting 'www' and github back in sync.
We also had to tweak this compared to the current internal version to
accomodate a recent change that makes 'editOnBeforeInput' and the other
handlers take 'editor' as an explicit argument instead of assumming
'this' will be the editor;
https://github.com/facebook/draft-js/commit/e64c2c3f2a3654b925b18baff448100cfbbf3738
**Update:**
**Also thanks to @davidchang for pinging me about landing this, @colinjeane for reporting this bug in #917 and submitting a nearly identical fix: https://github.com/facebook/draft-js/pull/919**
The delay on landing this was until 'setImmediate' was available in fbjs.[1]
[1]: …

Improved version of "Fix modifying state during onChange ... #667"

---

src/component/base/DraftEditorProps.js

In one case it seems the return type was just incorrect. We also
clarified the comments for 'keyBindingFn' in order to avoid confusion -
previously due to some Flow issues we had almost changed this flow type
to be incorrect. See https://github.com/facebook/draft-js/pull/894
Also fixes a hanging comma lint.

Fix Flow nits in DraftEditorProps

---

src/model/immutable/EditorState.js

This fixes a minor flow error coming up in a FB use case, and makes the
overall typing more consistent in this file.

Make 'decorator' optional and allow null consistenly in EditorState

---

README.md
docs/APIReference-APIMigration.md
docs/APIReference-ContentState.md
docs/APIReference-Data-Conversion.md
docs/APIReference-Editor.md
docs/APIReference-Entity.md
docs/Advanced-Topics-Block-Components.md
docs/Advanced-Topics-Decorators.md
docs/Advanced-Topics-Entities.md
docs/Advanced-Topics-Inline-Styles.md
docs/Advanced-Topics-Managing-Focus.md
docs/Overview.md
docs/QuickStart-API-Basics.md
docs/QuickStart-Rich-Styling.md

I haven't proof-read this yet, so reviews are very welcome.
Planning to merge this immediately after releasing 0.10.0, so within the next 24 hours or so. This updates all the documentation to use the new v0.10 syntax for Entity management, and points example links to the v0.10 examples.
It also adds an API Upgrade guide, under 'Advanced Topics'. I'd really love feedback on that, and improvements are welcome even after we land this! 🌱 
Thanks to everyone who has other documentation PRs open, and to everyone who has been patient while we test and prepare v0.10.

Update docs for v0.10

---

docs/Advanced-Topics-Entities.md

**Summary**
Fix runtime error in the example code caused by typo.
**Test Plan**
No functional changes.

Fix typo in docs

---

docs/Advanced-Topics-Decorators.md

fix the version in the link to make the link to the decorator/tweet example valid

documentation: fix version in the link

---

website/core/Site.js
website/layout/DocsLayout.js

Adds documentation page title as a prefix to `<title>` tag in site header as proposed in https://github.com/facebook/draft-js/issues/965. For example, "Custom Block Components | Draft.js | Rich Text Editor Framework for React" would be the title for the "Custom Block Components" page.
Implements `pageTitle` prop on the `Site` component to accomplish this. If `titlePrefix` is not available, it will fall back to "Draft.js | Rich Text Editor Framework for React".

Add documentation page title to header data

---

docs/APIReference-Data-Conversion.md
docs/APIReference-Editor.md
docs/Advanced-Topics-Block-Components.md
docs/Advanced-Topics-Decorators.md
docs/Advanced-Topics-Inline-Styles.md
docs/Advanced-Topics-Managing-Focus.md
docs/QuickStart-API-Basics.md
docs/QuickStart-Rich-Styling.md

fix version of the draft.js in the links to the examples in the documentation

documentation: fix links to the examples

---

website/core/Site.js

Following https://github.com/facebook/draft-js/pull/972, reuse prefixed page title strings for `og:title` metatag on the documentation pages.

documentation: share prefixed Title string with og:title metatag

---

meta/roadmaps/2017-h1.md

This roadmap was reviewed by the core contributors during a weekly
meeting and represents our current ideas about project direction.
The roadmap will evolve over time, and we'll be adding weekly notes in
this 'meta' directory in order to provide more fresh and detailed
updates about project direction.
Why use the 'meta' directory instead of a 'blog' or 'wiki'?
- People following the repo can get notifications push to them when 'meta' is updated.
- Allows roadmap to be living, breathing document with updates as time goes by
- Allows collaboration/discussion from community
- We are taking weekly meeting notes anyway; let people know that we are meeting and making progress
Similar to the [Relay repository's 'meta' directory](https://github.com/facebook/relay/tree/master/meta).
Thanks to …

Add H1 2017 Roadmap Update and '/meta' directory

---

src/model/encoding/__tests__/convertFromRawToDraftState-test.js
src/model/encoding/convertFromRawToDraftState.js

**Summary**
In instances where type is undefined or null, this would be used as type due to the way type is destructured from each `block` in `contentBlocks`. This commit adds to a default value which ensure any falsey is changed to `unstyled` ensure the returned ContentBlock always has a valid DraftBlockType as its type. A similar approach in this file exists for all other values that are extracted from each block.
**Test Plan**
- As this change is within `model` the test plan is to use a unit test to validate the behavior that is expected after the change.
- Running the test without the change shows that this behavior was not present prior.

Add default value for type in convertFromRawToDraftState

---

src/model/immutable/__tests__/EditorState-test.js

For issue https://github.com/facebook/draft-js/issues/873, adds test to `EditorState` to check that `getDecorations` is called with desired argument types and in the proper order.

Test that `getDecorations` is called with correct arguments

---

website/server/generate.js

This should fix #1029. The glob pattern in `website/server/generate.js` was including directories when it really only cares about files.

Only include files in glob, not directory.

---

website/server/convert.js

There was a race condition in the website generation script (`generate.js`). It calls `convert.js` to convert Markdown to JavaScript, and then immediately looks for the resulting JavaScript files. However, `convert.js` uses the async version of `glob()`. This means that the code in generate.js that looks for these files can execute **before** the conversion in convert.js finishes, resulting in no pages being built. When this happens on TravisCI, it deletes all the pages on the site, due to the `rm -Rf *` in `publish.sh`.
I've simply switched `convert.js` to use the synchronous version of `glob()` so that it's guaranteed to finish before the generation happens.
This diff looks large, but most of it is changing the indentation level as the code is no longer in a callback.
References #1029

Fix race condition in website builder script

---

docs/Advanced-Topics-Key-Bindings.md

**Summary**
Updated docs to show proper way to bind functions when using them inside render. By binding them in the constructor it prevents bind from getting called on each render.
Some more thoughts on proper binding:
https://daveceddia.com/avoid-bind-when-passing-props/
**Test Plan**
No Test Plan needed. Just updated docs.

Small update keybinding docs.

---

website/src/css/draft.css

This pull request changes the base font-weight in the website docs from 300 to normal. These old eyes find it easier to read and it is the same font-weight as the React website docs.

Change website main font-weight to normal.

---

src/model/modifier/DraftModifier.js
src/model/modifier/getCharacterRemovalRange.js

There's a bug with deletion of segmented and immutable entities when they are not fully selected and only part of a selection. The bug is documented in #1063.
This fixes #1063 so that when deleting (such as through backspace) after having made a selection that contains part of an immutable or segmented entity, the entity text deletion is now correctly handled.

Correctly delete immutable and segmented entity content when at the edge of a selection

---

docs/APIReference-Editor.md
docs/Advanced-Topics-Issues-and-Pitfalls.md
docs/Overview.md
src/component/base/DraftEditorProps.js
website/README.md

i think this covers all the bases from #1072, namely it explains in
detail what the effects are of using the prop and when it is or is
not necessary for most consumers and what the potential behavior might
be if used carelessly.
also adds in a small change to homepage install/polyfill gotcha for
anyone that is running into that problem (i am just guessing that i
can't be the only one that has forgotten that ie11 is devoit of fancy
string methods).
feel free to cherry-pick away any of these commits as needed.

add documentation for `editorKey` prop

---

src/model/modifier/DraftModifier.js
src/model/modifier/getCharacterRemovalRange.js

Reverts facebook/draft-js#1065
It looks like this PR may introduce some subtle bugs with entity deletion - going to revert it while we investigate.

Revert "Correctly delete immutable and segmented entity content when at the edge of a selection"

---

src/component/handlers/edit/editOnInput.js

Related to issue #1011
There is a bug in Android 5.1 (not 5.0 oddly enough) that makes text
entry nearly unusable. It's documented in detail here -
https://github.com/facebook/draft-js/issues/1011
Logging everything shows that;
- when we have a block with text and spaces, and start deleting the
characters one by one, there is an 'onInput' for each deletion that
updates the text.
- when you delete the very last character, the 'anchorNode' of the
domSelection has a type that is not a text node. So we skip updating
at all, and that means the last character doesn't actually get
properly deleted from editorState.
- Then the next time something fully updates the editorState, that last
character shows up again.
The root issue is that Android 5.1, when we tested it, was in
"composition" mode and …

Initial fix for text insertion bugs in Android 5.1

---

src/component/handlers/edit/editOnInput.js
src/component/utils/DraftFeatureFlags.js
src/model/modifier/DraftModifier.js
src/model/modifier/getCharacterRemovalRange.js

We use feature flags in the FB version of Draft to test new and
potentially unstable changes. This mirrors out the flags we currently
have and sets the stage for keeping things in sync going forward.
Now internal use of feature flags will not block syncing and releasing
Draft.
This is part of an effort to make releases simpler and more frequent,
and keep the internal and external versions of Draft in sync.
As part of matching up the internal and external Draft flags we added
the changes from PR #1065 by @mmmoussa, with the main change under a
flag that is set to false.
---Test Plan
Manually tested the examples in Chrome, and we will do the full test
plan before releasing v0.10.1.

Add Feature Flags in Draft, and add Entity Deletion change under Flag

---

src/component/base/DraftEditor.react.js
src/component/base/DraftEditorProps.js

Wanted: manual testing of this PR.
There is some really weird behavior in Android 5.0 when auto-correct happens.
More details here;
https://github.com/facebook/draft-js/issues/1010
Setting 'spellCheck' to 'false' didn't seem to be enough to stop this.
My quick fix for now is to expose more properties on Draft for
controlling autocorrect. This could also be useful to people in general,
since there are often complaints about autocorrect on mobile web.
Long term we will be addressing the root causes of the bugs with mobile
web, but this seems like a useful change regardless.
We did some testing with mobile web using these props.
Ideally I'd like to get testing done of each prop in each supported
browser, and document the effects. If anyone can help verify different
behaviors please comment …

Expose props for disabling auto-correct, auto-complete, auto-capitalize

---

.eslintignore

After running the build step for the 'universal' example there is a bundle file which we don't want to lint. This fixes the issue.
Steps to reproduce the problem:
- install dependencies and run `npm run demo` in the universal example directory.
- then run `npm run lint` and see the errors from linting the `bundle.js` file

Add bundles from 'universal' example to eslintignore

---

src/component/base/DraftEditorProps.js
src/component/handlers/edit/editOnBeforeInput.js
src/component/handlers/edit/editOnKeyDown.js
src/component/handlers/edit/editOnPaste.js

There have been bugs reported in cases where the users of Draft are
updating 'editorState' in their custom handlers for keyDown, paste, etc.
This can be a problem when they are using an 'editorState' that is in
the parent's props or state and is not in sync, at that moment, with the
editorState in Draft. This allows the parent to use the most updated
editorState in custom handlers.
This change was already reviewed by @spicyj and credit for this fix goes
to @alanouri for making this change.

Pass fresh editorState to edit handlers

---

src/component/base/DraftEditorProps.js
src/component/handlers/edit/editOnBeforeInput.js
src/component/handlers/edit/editOnKeyDown.js

I had mirrored parts of this change from FB to github but missed some
things. This is the second part of the same change - context below.
Earlier part merged as https://github.com/facebook/draft-js/pull/1112
---
There have been bugs reported in cases where the users of Draft are
updating 'editorState' in their custom handlers for keyDown, paste, etc.
This can be a problem when they are using an 'editorState' that is in
the parent's props or state and is not in sync, at that moment, with the
editorState in Draft. This allows the parent to use the most updated
editorState in custom handlers.
This change was already reviewed by @spicyj and credit for this fix goes
to @alanouri for making this change.

[Part 2] Pass fresh editorState to edit handlers

---

src/model/modifier/DraftModifier.js
src/model/modifier/__tests__/RichTextEditorUtil-test.js
src/model/modifier/getCharacterRemovalRange.js

**Summary**
Fixed bugs with entity deletion when the start and end of the selection are not in the same block. Also fixed a bug with the atomic block deletion test case which was identified when PR #1094 was opened.
**Test Plan**
Ensured all unit tests pass with the draft_segmented_entities_behavior feature flag enabled and disabled. Also tested all deletion edge cases related to mutable, segmented, and immutable entities, along with atomic block deletion.

Fixed bugs with deletion of entities between blocks and the atomic block deletion test case

---

gulpfile.js

Currently the `dist/Draft.js` script requires window globals for its two primarily dependencies, `Immutable` and `React`. Both of these packages actually publish UMD compatible wrappers in addition to falling back to exporting window globals. It'd be great if Draft.js could do the same.
Effective changes to `dist/Draft.js` output.
``` diff
diff --git a/Draft.js b/Draft.js
index 143a811..b6d0b26 100644
--- a/Draft.js
+++ b/Draft.js
@@ -8,8 +8,17 @@
* LICENSE file in the root directory of this source tree. An additional grant
* of patent rights can be found in the PATENTS file in the same directory.
*/
-var Draft =
-/******/ (function(modules) { // webpackBootstrap
+(function webpackUniversalModuleDefinition(root, factory) {
+	if(typeof exports === 'object' && typeof module === 'object')
+ …
```

Support UMD in dist output format

---

docs/Advanced-Topics-Entities.md

I made a mistake in merging in #1141. The `ContentState` returned by `ContentState.createEntity` is not a new `ContentState`. Instead of reverting #1141 I'm just opening a new PR with the small fix since it's documentation.

Fixed incorrect entity documentation

---

README.md
docs/Advanced-Topics-Entities.md

- Fix reference to older contentState
- Change `href` to `url` for consistency with "link" example in case people copy-paste between both (which I did today)
- Fix indentation in README

Docs tweaks

---

src/component/handlers/edit/editOnInput.js

Type `wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww` in Chrome. Click at the beginning of the second line. Press space. It no longer deletes your text. That's a good thing.
T17377963

Fix mystery text deletion

---

src/component/selection/setDraftEditorSelection.js
src/stubs/DraftJsDebugLogging.js

Since the main logging method is stubbed out, this should have no effect
on the open source Draft project. Adding this on Github in order to
continue syncing the internal and open source version of Draft, to
unblock releasing v0.10.1 of Draft.
Not waiting on review since this change was already reviewed internally at FB.
Context of this change:
We have gotten reports of an error thrown from `setDraftEditorSelection`
that completely breaks Draft functionality once it occurs. It happens
very inconsistently, across multiple browsers, and we have not yet been
able to find the root cause or reproduce it reliably. This logging may
help us get more information about the problem.

Add logging for hard-to-reproduce bug

---

src/component/base/DraftEditor.react.js

This should help a lot with "Failed to execute 'setStart' on 'Range'" exceptions we've logged in production and seen in bug reports.
Test Plan:
Type in editor, right-click in Chrome then "Translate to English", editing no longer breaks.

Mark editor element as notranslate

---

examples/draft-0-10-0/universal/package.json
examples/draft-0-9-1/universal/package.json

**Summary**
`package.json` for the "universal" example uses a semicolon to separate two commands (a `mkdir` command, and a `browserify` command). This syntax doesn't work on Windows. I've changed it to instead just have the directory as part of source control so it doesn't need to create it when executed.
**Test Plan**
`yarn run demo` on Windows, now it works!
Closes #1166

Fix "universal" demo on Windows.

---

examples/draft-0-10-0/convertFromHTML/convert.html
examples/draft-0-10-0/media/media.html
examples/draft-0-9-1/convertFromHTML/convert.html
examples/draft-0-9-1/media/media.html

Draft uses some ES6 syntax and assumes users will pair it with an ES6
polyfill. See
https://github.com/facebook/draft-js/blob/c12640f05e8328f5c97902c0c5e94a02ba9f58be/docs/Advanced-Topics-Issues-and-Pitfalls.md#polyfills
When testing some examples in IE they were not rendering, and threw an
error because we use `String.prototype.startsWith` in Draft.
**test plan:**
Open the 'convertFromHTML' and 'media' example files in IE, and they
will render.
**issue:**
https://github.com/facebook/draft-js/issues/1165

Add es6 polyfill to all examples

---

CHANGELOG.md

Adding annotations for the upcoming v0.10.1 release.
- saving time when actually doing the release
- transparency
**test plan:**
Visual inspection
**issue:**
https://github.com/facebook/draft-js/issues/1158

Add 'Unreleased' version of v0.10.1 change log

---

meta/meeting-notes/2017-03-10-weekly-meeting.md
meta/meeting-notes/2017-03-17-weekly-meeting.md
meta/meeting-notes/2017-03-24-weekly-meeting.md
meta/meeting-notes/2017-03-31-weekly-meeting.md
meta/meeting-notes/2017-04-14-weekly-meeting.md
meta/meeting-notes/2017-04-21-weekly-meeting.md
meta/meeting-notes/2017-04-28-weekly-meeting.md
meta/meeting-notes/2017-05-05-weekly-meeting.md

We had few things to note each week and were deferring updating the
meeting notes.
Based on [issue #1193](https://github.com/facebook/draft-js/issues/1193)
it sounds like the meeting notes will provide signal that the project is
still maintained.

Update weekly meeting notes from March-April 2017

---

docs/Overview.md

**Summary**
Mention the need to include `Draft.css` when rendering the editor in the overview doc and reference the link, https://draftjs.org/docs/advanced-topics-issues-and-pitfalls.html#missing-draft-css, to learn more about why it is needed. 
This is related to https://github.com/facebook/draft-js/issues/1201.
**Test Plan**
This is a doc update. There is probably no need for additional tests.

Add mention of draft css in overview doc

---

src/component/contents/__tests__/DraftEditorTextNode-test.js
src/component/handlers/edit/editOnCut.js
src/component/handlers/edit/editOnInput.js
src/component/selection/setDraftEditorSelection.js
src/model/decorators/__tests__/CompositeDraftDecorator-test.js
src/model/encoding/convertFromHTMLToContentBlocks.js

In order to enable auto-syncing between Github and www we need to get
both to a point were they are in sync.
This copies some misc. changes from the www version of Draft into the
Github version of Draft. We are pulling in some changes as well.
Includes changes from
D5070771 Fix errors with single new in context
(Note about above: TIL "by design you're not supposed to use new with Immutable.js data structures (well, except Records).")
D5172412 [codemod] disable automock by default on as many remaining tests in www as possible @bypass-lint
D5070207 [www][flowify] Start adding Flow typechecks to Style
D4966517 [TF] Minor comments and nits for the DraftJs Composer
D5109581 Add logging to catch Firefox Draft.js error
To enable auto-syncing, …

Copy over misc. changes from Facebook

---

src/component/base/__tests__/DraftEditor.react-test.js

We either check for the 'getEditorKey' method on the
'renderedComponent._instance' or the
'renderedComponent._instance._instance'
Internally we are using a different variation of the 'shallowRenderer'
and this test needs to run internally at Facebook as well as on Github.
This is not an ideal solution, but we can continue improving this test
once cleaning up the inconsistencies between Facebook and Github.
**test plan:**
`jest src/component/base/__tests__/DraftEditor.react-test.js`
Since I have limited time to work on this I will probably merge if/when CI passes.
**issue:**
https://github.com/facebook/draft-js/issues/1244

Tweak syntax of accessing '_instance' in DraftEditor test

---

.gitignore
examples/draft-0-10-0/universal/.gitignore
examples/draft-0-9-1/universal/.gitignore

**Summary**
Fixes #1111
- Moves all `.gitigores` to top level
- adds `yarn.lock` to gitignore
[...]
**Test Plan**
Verify using `git status` that the files continue to be ignored, and `yarn.lock` is now ignored
[...]

1111 - move all .gitignores to toplevel

---

src/Draft.js

Adds missing pragma.
This was causing a problem for users in some build set-ups.
Fixes #982
Thanks @yuku-t for this solution. :)
**test plan:**
Ran `yarn build` and inspected `lib/Draft.js.flow` before and after this
fix. It has the `@flow` pragma after, and did not before.
**issue:**
https://github.com/facebook/draft-js/issues/982

Add flow pragma to 'Draft.js'

---

docs/Advanced-Topics-Issues-and-Pitfalls.md

Based on issues from the community and internal experiments, we know
that there are severe bugs affecting some mobile web uses of Draft.js.
In particular, Android with certain keyboards and IME/rtl on Android.
This information is important for folks when deciding whether Draft.js
is the best choice for their use case. It may also get more interest in
improving Draft.js for mobile web use cases.
**test plan:**
Opened the docs and visually inspected. 
**issue:**
Related to https://github.com/facebook/draft-js/issues/1224

Add docs about lack of support for mobile browsers

---

src/component/utils/DraftFeatureFlags-core.js
src/stubs/DraftFeatureFlags.js

Credit to @spicyj for this approach. Planning to merge fast to unblock the sync script activation, but would love a review after-the-fact.
Moved 'DraftFeatureFlags' to 'stubs' directory, and make it export
'DraftFeatureFlags-core'.
The 'DraftFeatureFlags' file is, *I think*, the last file which is out
of sync with our internal FB version of Draft. That is because we
actually use different flag configs within FB than the defaults for OS.
**test plan:**
`yarn install && yarn build && yarn test` and play with example files
**issue:**
issue #1244

Move DraftFeatureFlags to stubs
